[package]
name = "live-helper-service"
version = "0.1.0"
authors = ["Mojtaba Zarezadeh <mojtab23@aol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12"
futures = "0.1"
